// Note: The table names (e.g., `firestore_export.charges_raw_latest`) are placeholders
// and will need to be updated with the actual names generated by the Firebase BigQuery extension.
// The project ID `lean-ehr` is also hardcoded and may need to be dynamic.

export const getFinancialSummaryQuery = `
WITH all_transactions AS (
  -- Charges
  SELECT
    PARSE_DATE('%Y-%m-%d', SUBSTR(JSON_EXTRACT_SCALAR(data, '$.occurrence_datetime'), 1, 10)) as event_date,
    'charge' as type,
    CAST(JSON_EXTRACT_SCALAR(data, '$.unit_price.value') AS NUMERIC) * CAST(JSON_EXTRACT_SCALAR(data, '$.quantity') AS NUMERIC) as amount,
    JSON_EXTRACT_SCALAR(data, '$.unit_price.currency') as currency
  FROM
    \`lean-ehr.firestore_export.charges_raw_latest\`
  UNION ALL
  -- Claims
  SELECT
    PARSE_DATE('%Y-%m-%d', SUBSTR(JSON_EXTRACT_SCALAR(data, '$.authored_on'), 1, 10)) as event_date,
    'claim' as type,
    CAST(JSON_EXTRACT_SCALAR(data, '$.total.value') AS NUMERIC) as amount,
    JSON_EXTRACT_SCALAR(data, '$.total.currency') as currency
  FROM
    \`lean-ehr.firestore_export.claims_raw_latest\`
  UNION ALL
  -- Payments
  SELECT
    PARSE_DATE('%Y-%m-%d', SUBSTR(JSON_EXTRACT_SCALAR(data, '$.occurrence_datetime'), 1, 10)) as event_date,
    'payment' as type,
    CAST(JSON_EXTRACT_SCALAR(data, '$.amount.value') AS NUMERIC) as amount,
    JSON_EXTRACT_SCALAR(data, '$.amount.currency') as currency
  FROM
    \`lean-ehr.firestore_export.payments_raw_latest\`
  UNION ALL
  -- Adjustments
  SELECT
    PARSE_DATE('%Y-%m-%d', SUBSTR(JSON_EXTRACT_SCALAR(data, '$.authored_on'), 1, 10)) as event_date,
    'adjustment' as type,
    CAST(JSON_EXTRACT_SCALAR(data, '$.approved_amount.value') AS NUMERIC) as amount,
    JSON_EXTRACT_SCALAR(data, '$.approved_amount.currency') as currency
  FROM
    \`lean-ehr.firestore_export.adjustments_raw_latest\`
)
SELECT
  FORMAT_DATE('%Y-%m-%d', event_date) as date,
  ANY_VALUE(currency) as currency,
  SUM(CASE WHEN type = 'charge' THEN amount ELSE 0 END) as charges,
  SUM(CASE WHEN type = 'claim' THEN amount ELSE 0 END) as claims,
  SUM(CASE WHEN type = 'payment' THEN amount ELSE 0 END) as payments,
  SUM(CASE WHEN type = 'adjustment' THEN amount ELSE 0 END) as adjustments
FROM
  all_transactions
GROUP BY
  event_date
ORDER BY
  event_date;
`

export const getResidentGrowthQuery = `
SELECT
  FORMAT_DATE('%Y-%m-%d', PARSE_DATE('%Y-%m-%d', SUBSTR(JSON_EXTRACT_SCALAR(data, '$.created_at'), 1, 10))) as created_at,
  -- This query is a placeholder for fetching resident data for growth calculation.
  -- The actual implementation will depend on the final schema in BigQuery.
FROM
  \`lean-ehr.firestore_export.residents_raw_latest\`
`
