import { z } from 'zod'
import {
  AllergySchema,
  DiagnosticHistorySchema,
  EmarRecordSchema,
  EmergencyContactSchema,
  AccountSchema,
  ChargeSchema,
  ClaimSchema,
  CoverageSchema,
  PaymentSchema,
  AdjustmentSchema,
  ObservationSchema,
  PrescriptionSchema,
  CarePlanSchema,
  CarePlanActivitySchema,
  GoalSchema,
  ProcedureSchema,
  TaskSchema,
  EncounterSchema,
  EpisodesOfCareSchema,
  IdentifierSchema,
  AddressSchema,
} from './schemas'
import {
  EncryptedAllergySchema,
  EncryptedDiagnosticHistorySchema,
  EncryptedEmarRecordSchema,
  EncryptedEmergencyContactSchema,
  EncryptedAccountSchema,
  EncryptedChargeSchema,
  EncryptedClaimSchema,
  EncryptedCoverageSchema,
  EncryptedPaymentSchema,
  EncryptedAdjustmentSchema,
  EncryptedObservationSchema,
  EncryptedPrescriptionSchema,
  EncryptedCarePlanSchema,
  EncryptedCarePlanActivitySchema,
  EncryptedGoalSchema,
  EncryptedProcedureSchema,
  EncryptedTaskSchema,
  EncryptedEncounterSchema,
  EncryptedEpisodesOfCareSchema,
  EncryptedIdentifierSchema,
  EncryptedAddressSchema,
} from './encrypted-schemas'
import {
  decryptAllergy,
  getAllergiesConverter,
  decryptDiagnosticHistory,
  getDiagnosticHistoryConverter,
  decryptEmarRecord,
  getEmarRecordConverter,
  decryptEmergencyContact,
  getEmergencyContactsConverter,
  decryptAccount,
  getAccountsConverter,
  decryptCharge,
  getChargesConverter,
  decryptClaim,
  getClaimsConverter,
  decryptCoverage,
  getCoveragesConverter,
  decryptPayment,
  getPaymentsConverter,
  decryptAdjustment,
  getAdjustmentsConverter,
  decryptObservation,
  getObservationsConverter,
  decryptPrescription,
  getPrescriptionsConverter,
  decryptCarePlan,
  getCarePlansConverter,
  decryptCarePlanActivity,
  getCarePlanActivitiesConverter,
  decryptGoal,
  getGoalsConverter,
  decryptProcedure,
  getProceduresConverter,
  decryptTask,
  getTasksConverter,
  decryptEncounter,
  getEncountersConverter,
  decryptEpisodesOfCare,
  getEpisodesOfCareConverter,
  decryptIdentifier,
  getIdentifiersConverter,
  decryptAddress,
  getAddressesConverter,
} from './converters'

export const subCollectionMap = {
  emergency_contacts: {
    converter: getEmergencyContactsConverter,
    decryptor: decryptEmergencyContact,
    schema: EmergencyContactSchema,
    encrypted_schema: EncryptedEmergencyContactSchema,
    kekType: 'contact',
  },
  accounts: {
    converter: getAccountsConverter,
    decryptor: decryptAccount,
    schema: AccountSchema,
    encrypted_schema: EncryptedAccountSchema,
    kekType: 'financial',
  },
  charges: {
    converter: getChargesConverter,
    decryptor: decryptCharge,
    schema: ChargeSchema,
    encrypted_schema: EncryptedChargeSchema,
    kekType: 'financial',
  },
  claims: {
    converter: getClaimsConverter,
    decryptor: decryptClaim,
    schema: ClaimSchema,
    encrypted_schema: EncryptedClaimSchema,
    kekType: 'financial',
  },
  coverages: {
    converter: getCoveragesConverter,
    decryptor: decryptCoverage,
    schema: CoverageSchema,
    encrypted_schema: EncryptedCoverageSchema,
    kekType: 'financial',
  },
  payments: {
    converter: getPaymentsConverter,
    decryptor: decryptPayment,
    schema: PaymentSchema,
    encrypted_schema: EncryptedPaymentSchema,
    kekType: 'financial',
  },
  adjustments: {
    converter: getAdjustmentsConverter,
    decryptor: decryptAdjustment,
    schema: AdjustmentSchema,
    encrypted_schema: EncryptedAdjustmentSchema,
    kekType: 'financial',
  },
  allergies: {
    converter: getAllergiesConverter,
    decryptor: decryptAllergy,
    schema: AllergySchema,
    encrypted_schema: EncryptedAllergySchema,
    kekType: 'clinical',
  },
  prescriptions: {
    converter: getPrescriptionsConverter,
    decryptor: decryptPrescription,
    schema: PrescriptionSchema,
    encrypted_schema: EncryptedPrescriptionSchema,
    kekType: 'clinical',
  },
  observations: {
    converter: getObservationsConverter,
    decryptor: decryptObservation,
    schema: ObservationSchema,
    encrypted_schema: EncryptedObservationSchema,
    kekType: 'clinical',
  },
  diagnostic_history: {
    converter: getDiagnosticHistoryConverter,
    decryptor: decryptDiagnosticHistory,
    schema: DiagnosticHistorySchema,
    encrypted_schema: EncryptedDiagnosticHistorySchema,
    kekType: 'clinical',
  },
  emar: {
    converter: getEmarRecordConverter,
    decryptor: decryptEmarRecord,
    encrypted_schema: EncryptedEmarRecordSchema,
    schema: EmarRecordSchema,
    kekType: 'clinical',
  },
  care_plans: {
    converter: getCarePlansConverter,
    decryptor: decryptCarePlan,
    schema: CarePlanSchema,
    encrypted_schema: EncryptedCarePlanSchema,
    kekType: 'clinical',
  },
  care_plan_activities: {
    converter: getCarePlanActivitiesConverter,
    decryptor: decryptCarePlanActivity,
    schema: CarePlanActivitySchema,
    encrypted_schema: EncryptedCarePlanActivitySchema,
    kekType: 'clinical',
  },
  goals: {
    converter: getGoalsConverter,
    decryptor: decryptGoal,
    schema: GoalSchema,
    encrypted_schema: EncryptedGoalSchema,
    kekType: 'clinical',
  },
  procedures: {
    converter: getProceduresConverter,
    decryptor: decryptProcedure,
    schema: ProcedureSchema,
    encrypted_schema: EncryptedProcedureSchema,
    kekType: 'clinical',
  },
  tasks: {
    converter: getTasksConverter,
    decryptor: decryptTask,
    schema: TaskSchema,
    encrypted_schema: EncryptedTaskSchema,
    kekType: 'clinical',
  },
  encounters: {
    converter: getEncountersConverter,
    decryptor: decryptEncounter,
    schema: EncounterSchema,
    encrypted_schema: EncryptedEncounterSchema,
    kekType: 'clinical',
  },
  episodes_of_care: {
    converter: getEpisodesOfCareConverter,
    decryptor: decryptEpisodesOfCare,
    schema: EpisodesOfCareSchema,
    encrypted_schema: EncryptedEpisodesOfCareSchema,
    kekType: 'clinical',
  },
  identifiers: {
    converter: getIdentifiersConverter,
    decryptor: decryptIdentifier,
    schema: IdentifierSchema,
    encrypted_schema: EncryptedIdentifierSchema,
    kekType: 'general',
  },
  addresses: {
    converter: getAddressesConverter,
    decryptor: decryptAddress,
    schema: AddressSchema,
    encrypted_schema: EncryptedAddressSchema,
    kekType: 'contact',
  },
}

export type SubCollectionMapType = typeof subCollectionMap

export type SubCollectionKey = keyof SubCollectionMapType

export type AllCollectionData = {
  [P in SubCollectionKey]?: z.infer<SubCollectionMapType[P]['schema']>[]
}
