"use client";
import { zodResolver } from "@hookform/resolvers/zod";
import { useForm } from "react-hook-form";
import { z } from "zod";
import { useRouter } from "next/navigation";
import { useState } from "react";

import { toast } from "@/components/ui/use-toast";
import { isError } from "@/app/utils";
import { addNewResident } from "@/app/admin/residents/actions/add";
import { ResidentFormBase } from "./ResidentFormBase";
import type { Resident, Nullable } from "@/types/resident";

const emergencyContactSchema = z.object({
  contact_name: z
    .string()
    .min(3, {
      message: "contact name must be at least 3 characters.",
    })
    .nullable()
    .optional(),
  cell_phone: z.string(),
  home_phone: z.string().nullable().optional(),
  work_phone: z.string().nullable().optional(),
  relationship: z.string().nullable().optional(),
});

const ResidentFormSchema = z.object({
  resident_name: z.string().nullable(),
  emergencyContacts: z.array(emergencyContactSchema).nullable().optional(),
});

interface ResidentFormAddProps {
  residence_id: string;
}

export function ResidentFormAdd({ residence_id }: ResidentFormAddProps) {
  const router = useRouter();
  const [noOfEmContacts, setNoOfEmContacts] = useState(0);

  const form = useForm<z.infer<typeof ResidentFormSchema>>({
    resolver: zodResolver(ResidentFormSchema),
    defaultValues: {
      resident_name: "",
      emergencyContacts: [],
    },
  });

  async function onSubmit(data: z.infer<typeof ResidentFormSchema>) {
    let residentData: Resident = {} as Resident;
    residentData.resident_name = data.resident_name ?? null;
    residentData.residence_id = residence_id;
    residentData.resident_id = ""; // New resident, ID will be generated by Firestore

    if (data.emergencyContacts) {
      residentData.emergencyContacts = data.emergencyContacts.map((contact) => ({
        work_phone: contact.work_phone ?? null,
        home_phone: contact.home_phone ?? null,
        contact_name: contact.contact_name ?? null,
        relationship: contact.relationship ?? null,
        cell_phone: contact.cell_phone,
      }));
    } else {
      residentData.emergencyContacts = null;
    }

    try {
      const { message, success } = await addNewResident(residentData);
      if (!success) {
        toast({
          title: success ? "Unable to Add New Resident" : message,
          variant: "destructive",
        });
        return;
      }
      toast({ title: message });
      form.reset({ resident_name: "", emergencyContacts: [] });
    } catch (err) {
      if (isError(err)) toast({ title: err.message, variant: "destructive" });
    }
  }

  return (
    <ResidentFormBase
      form={form}
      noOfEmContacts={noOfEmContacts}
      setNoOfEmContacts={setNoOfEmContacts}
      onSubmit={onSubmit}
      formTitle="Add A New Resident"
    />
  );
}
