export * from './residents'
export * from './residents/allergies'
export * from './residents/diagnostics'
export * from './residents/emar'
export * from './residents/emergencyContacts'
export * from './residents/financials'
export * from './residents/observations'
export * from './residents/prescriptions'
